# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to publish to: latest | next'
        required: false
        default: 'latest'
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    outputs:
      npm_tag: ${{github.event.inputs.tag}}
    steps:
      - name: Check Tag Name
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag != 'latest' && github.event.inputs.tag != 'next' }}
        run: |
          echo 'Only the tags "latest" or "next" are supported. You entered "${{ github.event.inputs.tag }}"'
          exit 1
      - echo "published to npm"

  ci-notify:
    needs: publish-npm
    uses: adobe/reactor-uploader/.github/workflows/notify.yaml@master
    with:
      tag: ${{github.event.inputs.tag}}
