name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: 'string'

jobs:
  simple-echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "got in here"
  notify-on-success:
    runs-on: ubuntu-latest
    if: ${{ inputs.tag == 'latest'}}
    steps:
      - run: echo "tag was $inputs.tag"
